language: ruby
sudo: false
cache: bundler
before_install:
 - sh ci/install_po4a.sh
script:
 - bundle exec make all
addons:
  apt:
    packages:
      - libunicode-linebreak-perl
notifications:
  email:
    on_success: never
    on_failure: always
